name: Pull Request

on: [pull_request]

jobs:
  prchecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.2
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Prepare for Jest (frontend)
        run: yarn install --frozen-lockfile
        working-directory: ./services/ui-src
      - name: Jest (frontend)
        run: yarn test
        working-directory: ./services/ui-src
      - name: Prepare for Jest (API)
        run: yarn install --frozen-lockfile
        working-directory: ./services/app-api
      - name: Jest (API)
        run: yarn test
        working-directory: ./services/app-api
  assignAuthor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assign PR to Creator
        run: |
          if [ "$PR_AUTHOR_TYPE" != "Bot" ]
            then
              gh pr edit $PRNUM --add-assignee $PR_AUTHOR
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_AUTHOR_TYPE: ${{ github.event.pull_request.user.type }}
